### ISSUE TITLE
How to add star rating programmatically on a view

### ISSUE THREAD

**Issue by hardikamal** [AppceleratorSolutions/AlloyWidgets#5]
I m trying to create a custom popup whee user can give rating.How to add star rating programmatically on a view.

I have tried using this but this is not working...
var starratingview = Alloy.createWidget('starrating', {
    max : '5',
    initialRating : '2.5',
    top : "20dp",
    layout : 'horizontal',
    width : Ti.UI.SIZE,
    height : '24dp',
    bottom : '20dp',
    editable : 'true',
});

popupview.add(starratingview);
starratingview.init();
starratingview.setRating(user.avgrating);

**Comment by skypanther** [comment]
I think all you're missing is the `.getView()`

```
popupview.add(starratingview.getView());
```

**Comment by hardikamal** [comment]
Yeah thanks
